services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: boundless-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_Strong!Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - boundless-sql-data:/var/opt/mssql

volumes:
  boundless-sql-data:
